[nixpacks]
language = "python"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18", "gcc"]

[phases.install]
cmds = [
  "python311 -m pip install --upgrade pip",
  "python311 -m pip install -r requirements.txt",
  "cd telegram-bot && npm install"
]

[start]
cmd = "cd backend && python311 -m gunicorn -w 4 -b 0.0.0.0:8080 --pythonpath . main:app"