[nixpacks]
language = "python"
[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:8080 backend.main:app"