[nixpacks]
language = "python"

[phases.setup]
nixPkgs = ["python311", "gcc", "libffi", "openssl"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "cd backend && gunicorn -w 4 -b 0.0.0.0:8080 main:app"