[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.watchPaths]
paths = ["backend/**", "requirements.txt", ".nixpacks.toml"]

[environments.production]
variables = { FLASK_ENV = "production", USE_WEBHOOK = "true", RUN_MODE = "webhook" }