/**
 * Глобальні константи для реферальної системи
 */
window.ReferralConstants = (function() {
  'use strict';

  // actionTypes.js
  const LevelRewardsActionTypes = {
    FETCH_LEVEL_REWARDS_REQUEST: 'FETCH_LEVEL_REWARDS_REQUEST',
    FETCH_LEVEL_REWARDS_SUCCESS: 'FETCH_LEVEL_REWARDS_SUCCESS',
    FETCH_LEVEL_REWARDS_FAILURE: 'FETCH_LEVEL_REWARDS_FAILURE',
    UPDATE_LEVEL1_REWARDS: 'UPDATE_LEVEL1_REWARDS',
    UPDATE_LEVEL2_REWARDS: 'UPDATE_LEVEL2_REWARDS',
    FETCH_REWARDS_HISTORY_REQUEST: 'FETCH_REWARDS_HISTORY_REQUEST',
    FETCH_REWARDS_HISTORY_SUCCESS: 'FETCH_REWARDS_HISTORY_SUCCESS',
    FETCH_REWARDS_HISTORY_FAILURE: 'FETCH_REWARDS_HISTORY_FAILURE',
    CLEAR_LEVEL_REWARDS_ERROR: 'CLEAR_LEVEL_REWARDS_ERROR'
  };

  // activityThresholds.js
  const MIN_DRAWS_PARTICIPATION = 3;
  const MIN_INVITED_REFERRALS = 1;

  // badgeRewards.js
  const BRONZE_BADGE_REWARD = 2500;
  const SILVER_BADGE_REWARD = 5000;
  const GOLD_BADGE_REWARD = 10000;
  const PLATINUM_BADGE_REWARD = 20000;

  const BADGE_REWARDS = {
    BRONZE: BRONZE_BADGE_REWARD,
    SILVER: SILVER_BADGE_REWARD,
    GOLD: GOLD_BADGE_REWARD,
    PLATINUM: PLATINUM_BADGE_REWARD
  };

  function getRewardByBadgeType(badgeType) {
    return BADGE_REWARDS[badgeType] || 0;
  }

  // badgeThresholds.js
  const BRONZE_BADGE_THRESHOLD = 25;
  const SILVER_BADGE_THRESHOLD = 50;
  const GOLD_BADGE_THRESHOLD = 100;
  const PLATINUM_BADGE_THRESHOLD = 500;

  const BADGE_THRESHOLDS = {
    BRONZE: BRONZE_BADGE_THRESHOLD,
    SILVER: SILVER_BADGE_THRESHOLD,
    GOLD: GOLD_BADGE_THRESHOLD,
    PLATINUM: PLATINUM_BADGE_THRESHOLD
  };

  const BADGE_TYPES = ['BRONZE', 'SILVER', 'GOLD', 'PLATINUM'];

  // directBonuses.js
  const DIRECT_BONUS_AMOUNT = 50;

  // rewardRates.js
  const LEVEL_1_REWARD_RATE = 0.1;
  const LEVEL_2_REWARD_RATE = 0.05;

  // taskThresholds.js
  const REFERRAL_TASK_THRESHOLD = 100;
  const REFERRAL_TASK_REWARD = 12000;
  const ACTIVE_REFERRALS_TASK_THRESHOLD = 50;
  const ACTIVE_REFERRALS_TASK_REWARD = 6000;

  const TASK_THRESHOLDS = {
    REFERRAL_COUNT: {
      threshold: REFERRAL_TASK_THRESHOLD,
      reward: REFERRAL_TASK_REWARD,
      title: 'Запросити 100 рефералів',
      description: 'Запросіть 100 нових користувачів та отримайте додаткову винагороду'
    },
    ACTIVE_REFERRALS: {
      threshold: ACTIVE_REFERRALS_TASK_THRESHOLD,
      reward: ACTIVE_REFERRALS_TASK_REWARD,
      title: 'Залучити 50 активних рефералів',
      description: 'Залучіть 50 активних користувачів для отримання винагороди'
    }
  };

  const TASK_TYPES = Object.keys(TASK_THRESHOLDS);

  // urlPatterns.js
  const REFERRAL_URL_PATTERN = 'Winix/referral/{id}';

  // Публічний API
  return {
    LevelRewardsActionTypes: LevelRewardsActionTypes,
    MIN_DRAWS_PARTICIPATION: MIN_DRAWS_PARTICIPATION,
    MIN_INVITED_REFERRALS: MIN_INVITED_REFERRALS,
    BRONZE_BADGE_REWARD: BRONZE_BADGE_REWARD,
    SILVER_BADGE_REWARD: SILVER_BADGE_REWARD,
    GOLD_BADGE_REWARD: GOLD_BADGE_REWARD,
    PLATINUM_BADGE_REWARD: PLATINUM_BADGE_REWARD,
    BADGE_REWARDS: BADGE_REWARDS,
    getRewardByBadgeType: getRewardByBadgeType,
    BRONZE_BADGE_THRESHOLD: BRONZE_BADGE_THRESHOLD,
    SILVER_BADGE_THRESHOLD: SILVER_BADGE_THRESHOLD,
    GOLD_BADGE_THRESHOLD: GOLD_BADGE_THRESHOLD,
    PLATINUM_BADGE_THRESHOLD: PLATINUM_BADGE_THRESHOLD,
    BADGE_THRESHOLDS: BADGE_THRESHOLDS,
    BADGE_TYPES: BADGE_TYPES,
    DIRECT_BONUS_AMOUNT: DIRECT_BONUS_AMOUNT,
    LEVEL_1_REWARD_RATE: LEVEL_1_REWARD_RATE,
    LEVEL_2_REWARD_RATE: LEVEL_2_REWARD_RATE,
    REFERRAL_TASK_THRESHOLD: REFERRAL_TASK_THRESHOLD,
    REFERRAL_TASK_REWARD: REFERRAL_TASK_REWARD,
    ACTIVE_REFERRALS_TASK_THRESHOLD: ACTIVE_REFERRALS_TASK_THRESHOLD,
    ACTIVE_REFERRALS_TASK_REWARD: ACTIVE_REFERRALS_TASK_REWARD,
    TASK_THRESHOLDS: TASK_THRESHOLDS,
    TASK_TYPES: TASK_TYPES,
    REFERRAL_URL_PATTERN: REFERRAL_URL_PATTERN
  };
})();

// Для зворотної сумісності
window.DIRECT_BONUS_AMOUNT = window.ReferralConstants.DIRECT_BONUS_AMOUNT;
window.BRONZE_BADGE_THRESHOLD = window.ReferralConstants.BRONZE_BADGE_THRESHOLD;
window.SILVER_BADGE_THRESHOLD = window.ReferralConstants.SILVER_BADGE_THRESHOLD;
window.GOLD_BADGE_THRESHOLD = window.ReferralConstants.GOLD_BADGE_THRESHOLD;
window.PLATINUM_BADGE_THRESHOLD = window.ReferralConstants.PLATINUM_BADGE_THRESHOLD;
window.BRONZE_BADGE_REWARD = window.ReferralConstants.BRONZE_BADGE_REWARD;
window.SILVER_BADGE_REWARD = window.ReferralConstants.SILVER_BADGE_REWARD;
window.GOLD_BADGE_REWARD = window.ReferralConstants.GOLD_BADGE_REWARD;
window.PLATINUM_BADGE_REWARD = window.ReferralConstants.PLATINUM_BADGE_REWARD;